export const FETCH_COUNTRIES_INFO = "FETCH_COUNTRIES_INFO";
export const FETCH_COUNTRY_NAMES = "FETCH_COUNTRY_NAMES";
export const FETCH_COUNTRY_INFO = "FETCH_COUNTRY_INFO";
export const SELECTED_REGION = "SELECTED_REGION";
export const CHECK_COUNTRY = "CHECK_COUNTRY";
export const COUNTRY_CHECKED = "COUNTRY_CHECKED";
export const SELECTED_COUNTRY = "SELECTED_COUNTRY";
export const UNSELECTED_COUNTRY = "UNSELECTED_COUNTRY";



